### PR TITLE
Added Dockerfile + Cleaned CMakeLists

### PR DESCRIPTION
**Pull request by nily-dti**

### CODE REVIEW

**Comment by pantor** [comment]
Hi! Thanks so much for contributing!

However this PR has quite a few different topics, so there are a few issues/questions from my side:

1. I would like to leave the robots IP address as `172.16.0.2`, as this one is also used in the official Franka docs.

2. Is Docker really that useful for frankx, as there are a lot of hard real-time requirements. Do you know how Docker handles that?

3. Your API for locking and unlocking the brakes looks really good!

**Comment by nily-dti** [comment]
You're welcome and thank you for sharing your research!

I know that this PR is not straight after the book 👍 

1. The robot's IP can easily remain `172.16.0.2`. I have no issues with that. I simply forgot to change it back
1. Docker is very useful as it does direct kernel calls (as opposed to VMs), but it does require privileged rights to allow the docker user to set the RT. We have run several communication experiments @dti-research that shows no difference between running native installs vs. docker. I would, without hesitation, recommend using Docker for the Franka Emika Panda robot 👍  
1. Thank you. It might be possible to extend this further if a need comes up.

**Comment by nily-dti** [comment]
Is there something I should change prior to merging?

**Comment by pantor** [comment]
I've now included the Dockerfile, an improved CMakeLists, the api for opening and closing the brakes, and arguments for the robot's hostname in the master branch.

I've tried to push to this PR branch, but somehow I didn't have write access. So I've just committed to the master branch directly, I hope that's alright for you. So I'll close this PR.

**Comment by pantor** [comment]
And I've added a `stop_at_python_signal` boolean in the [Robot class](https://pantor.github.io/frankx/classfrankx_1_1_robot.html). So you can now disable the python checks at runtime, I hope that this fixes your issue as well.

**Pull request closed without merging**
